[package]
name = "syntect-tui"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A lightweight toolset for converting from syntect stylised text to tui stylisted text"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.9.2"
syntect = "5.0.0"
tui = "0.19.0"

[dev-dependencies]
rstest = "0.15"
