[package]
name = "syntect-tui"
version = "1.0.1"
edition = "2021"
license = "MIT"
description = "A lightweight translation layer between syntect.rs and tui.rs style types"
authors = ["Pierre Chanquion <{FORENAME}.{FIRST_FIVE_LETTERS_OF_SURNAME}.io>"]

[dependencies]
custom_error = "1.9.2"
syntect = "5.0.0"
tui = "0.19.0"

[dev-dependencies]
rstest = "0.15"
